/* THIS (.ts) FILE IS GENERATED BY TypedSignalR.Client.TypeScript */
/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import type { IStreamResult, Subject } from '@microsoft/signalr';
import type { JoinSessionDto, RestoreStateDto, ParticipantUpdateDto, ParticipantDto, ParticipantUpdateResponseDto } from '../Backend.Dto';

export type ISessionHub = {
    /**
    * @param data Transpiled from Backend.Dto.JoinSessionDto
    * @returns Transpiled from System.Threading.Tasks.Task<Backend.Dto.RestoreStateDto?>
    */
    joinSession(data: JoinSessionDto): Promise<RestoreStateDto>;
    /**
    * @param roomId Transpiled from string
    * @returns Transpiled from System.Threading.Tasks.Task
    */
    leaveRoom(roomId: string): Promise<void>;
    /**
    * @param data Transpiled from Backend.Dto.ParticipantUpdateDto
    * @returns Transpiled from System.Threading.Tasks.Task<bool>
    */
    updateParticipantData(data: ParticipantUpdateDto): Promise<boolean>;
}

export type ISessionHubClient = {
    /**
    * @param data Transpiled from Backend.Dto.ParticipantDto
    * @returns Transpiled from System.Threading.Tasks.Task
    */
    participantJoined(data: ParticipantDto): Promise<void>;
    /**
    * @param data Transpiled from Backend.Dto.ParticipantUpdateResponseDto
    * @returns Transpiled from System.Threading.Tasks.Task
    */
    participantUpdated(data: ParticipantUpdateResponseDto): Promise<void>;
}

