/* THIS (.ts) FILE IS GENERATED BY TypedSignalR.Client.TypeScript */
/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import type { HubConnection, IStreamResult, Subject } from '@microsoft/signalr';
import type { ISessionHub, ISessionHubClient } from './Backend.Hubs.Interfaces';
import type { JoinSessionDto, RestoreStateDto, ParticipantDto } from '../Backend.Dto';


// components

export type Disposable = {
    dispose(): void;
}

export type HubProxyFactory<T> = {
    createHubProxy(connection: HubConnection): T;
}

export type ReceiverRegister<T> = {
    register(connection: HubConnection, receiver: T): Disposable;
}

type ReceiverMethod = {
    methodName: string,
    method: (...args: any[]) => void
}

class ReceiverMethodSubscription implements Disposable {

    public constructor(
        private connection: HubConnection,
        private receiverMethod: ReceiverMethod[]) {
    }

    public readonly dispose = () => {
        for (const it of this.receiverMethod) {
            this.connection.off(it.methodName, it.method);
        }
    }
}

// API

export type HubProxyFactoryProvider = {
    (hubType: "ISessionHub"): HubProxyFactory<ISessionHub>;
}

export const getHubProxyFactory = ((hubType: string) => {
    if(hubType === "ISessionHub") {
        return ISessionHub_HubProxyFactory.Instance;
    }
}) as HubProxyFactoryProvider;

export type ReceiverRegisterProvider = {
    (receiverType: "ISessionHubClient"): ReceiverRegister<ISessionHubClient>;
}

export const getReceiverRegister = ((receiverType: string) => {
    if(receiverType === "ISessionHubClient") {
        return ISessionHubClient_Binder.Instance;
    }
}) as ReceiverRegisterProvider;

// HubProxy

class ISessionHub_HubProxyFactory implements HubProxyFactory<ISessionHub> {
    public static Instance = new ISessionHub_HubProxyFactory();

    private constructor() {
    }

    public readonly createHubProxy = (connection: HubConnection): ISessionHub => {
        return new ISessionHub_HubProxy(connection);
    }
}

class ISessionHub_HubProxy implements ISessionHub {

    public constructor(private connection: HubConnection) {
    }

    public readonly joinSession = async (data: JoinSessionDto): Promise<RestoreStateDto> => {
        return await this.connection.invoke("JoinSession", data);
    }

    public readonly leaveRoom = async (roomId: string): Promise<void> => {
        return await this.connection.invoke("LeaveRoom", roomId);
    }
}


// Receiver

class ISessionHubClient_Binder implements ReceiverRegister<ISessionHubClient> {

    public static Instance = new ISessionHubClient_Binder();

    private constructor() {
    }

    public readonly register = (connection: HubConnection, receiver: ISessionHubClient): Disposable => {

        const __participantJoined = (...args: [ParticipantDto]) => receiver.participantJoined(...args);

        connection.on("ParticipantJoined", __participantJoined);

        const methodList: ReceiverMethod[] = [
            { methodName: "ParticipantJoined", method: __participantJoined }
        ]

        return new ReceiverMethodSubscription(connection, methodList);
    }
}

