/* THIS (.ts) FILE IS GENERATED BY Tapper */
/* eslint-disable */
/* tslint:disable */
import type { BodyProfileEnum, ColorProfileEnum, FaceProfileEnum, HatProfileEnum, ParticipantRole, GameState } from './Backend.Models.Enums';

/** Transpiled from Backend.Dto.AnonymousProfilePictureDto */
export type AnonymousProfilePictureDto = {
    /** Transpiled from Backend.Models.Enums.BodyProfileEnum */
    body: BodyProfileEnum;
    /** Transpiled from Backend.Models.Enums.ColorProfileEnum */
    color: ColorProfileEnum;
    /** Transpiled from Backend.Models.Enums.FaceProfileEnum */
    face: FaceProfileEnum;
    /** Transpiled from Backend.Models.Enums.HatProfileEnum */
    hat: HatProfileEnum;
}

/** Transpiled from Backend.Dto.AnonymousUserDto */
export type AnonymousUserDto = {
    /** Transpiled from System.Guid */
    id: string;
    /** Transpiled from string */
    name: string;
}

/** Transpiled from Backend.Dto.JoinSessionDto */
export type JoinSessionDto = {
    /** Transpiled from string */
    roomCode: string;
    /** Transpiled from System.Guid */
    playerId?: string;
}

/** Transpiled from Backend.Dto.ParticipantDto */
export type ParticipantDto = {
    /** Transpiled from string */
    name: string;
    /** Transpiled from Backend.Dto.AnonymousProfilePictureDto */
    profilePicture: AnonymousProfilePictureDto;
}

/** Transpiled from Backend.Dto.PresenterDto */
export type PresenterDto = {
    /** Transpiled from string */
    userName: string;
    /** Transpiled from string? */
    profilePictureUrl?: string;
}

/** Transpiled from Backend.Dto.RestoreStateDto */
export type RestoreStateDto = {
    /** Transpiled from string */
    sessionName: string;
    /** Transpiled from string? */
    sessionDescription?: string;
    /** Transpiled from Backend.Models.Enums.ParticipantRole */
    role: ParticipantRole;
    /** Transpiled from Backend.Models.Enums.GameState */
    gameState: GameState;
    /** Transpiled from Backend.Dto.AnonymousUserDto? */
    userInformation?: AnonymousUserDto;
    /** Transpiled from Backend.Dto.PresenterDto */
    presenter: PresenterDto;
    /** Transpiled from System.Collections.Generic.List<Backend.Dto.ParticipantDto> */
    participants: ParticipantDto[];
}

